services:
  interactive_alma_reports:
    build: .
    container_name: interactive_alma_reports
    working_dir: /app
    volumes:
      - ./:/app
      - ./ini_local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./ini_local/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive_alma_reports.rule=Host(`interactive-alma-reports.wrlc.localhost`)"
      - "traefik.http.routers.interactive_alma_reports.tls=true"
      - "traefik.http.routers.interactive_alma_reports.entrypoints=websecure"
    secrets:
      - ssh_key
      - gitconfig
    networks:
      - proxy

secrets:
  ssh_key:
    file: ${SSH_KEY_FILE}
  gitconfig:
    file: ${GITCONFIG}

networks:
  proxy:
    external: true