name: Pull Request Review

on:
  pull_request:
    types:
      - opened

jobs:
  pull-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v3
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.READ_ORG_TOKEN }}
          username: ${{ github.actor }}
          team: ${{ vars.ADMIN_TEAM }}

      - name: Request reviews on opened PRs
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ vars.REVIEWERS }}
          reviewers: ${{ vars.REVIEWERS }}
          max-num-of-reviewers: 1
